comment some code to test

diff --git a/.github/workflows/package-helm-chart.yaml b/.github/workflows/package-helm-chart.yaml
--- a/.github/workflows/package-helm-chart.yaml
+++ b/.github/workflows/package-helm-chart.yaml
@@ -3,18 +3,18 @@ name: Package Helm Chart
 on:
   workflow_call:
     inputs:
-      jfrog_url:
-        description: "URL of Artifactory server"
-        type: string
-        default: "https://nethermind.jfrog.io"
+      # jfrog_url:
+      #   description: "URL of Artifactory server"
+      #   type: string
+      #   default: "https://nethermind.jfrog.io"
       chart_path:
         description: "Path to the Helm chart to package"
         type: string
         required: true
-    secrets:
-      artifactory_api_token:
-        description: "API token for JFrog Artifactory"
-        required: true
+    # secrets:
+    #   artifactory_api_token:
+    #     description: "API token for JFrog Artifactory"
+    #     required: true
 
 jobs:
   publish:
@@ -22,12 +22,6 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
-
-      - name: Clone Nethermind Helm Charts Repository
-        run: |
-          git clone https://github.com/NethermindEth/charts.git
-          cd charts
-          ls -l
 
       - name: Set up Helm
         uses: azure/setup-helm@v3
@@ -49,38 +43,39 @@ jobs:
           cd ${{ inputs.chart_path }}
           helm test .
 
-      - name: Check Backward Compatibility
-        id: backward-compatibility
-        run: |
-          cd ${{ inputs.chart_path }}
+      # - name: Check Backward Compatibility
+      #   id: backward-compatibility
+      #   run: |
+      #     cd ${{ inputs.chart_path }}
 
-          # Fetch the previous version of the chart from JFrog Artifactory
-          PREVIOUS_VERSION=$(helm show chart . | grep 'version:' | awk '{print $2}' | awk -F. '{print $1"."$2"."$3-1}')
-          CHART_NAME=$(grep 'name:' Chart.yaml | awk '{print $2}')
-          jf rt dl "helm-local/my-chart-$PREVIOUS_VERSION.tgz" --flat
+      #     # Fetch the previous version of the chart from JFrog Artifactory
+      #     PREVIOUS_VERSION=$(helm show chart . | grep 'version:' | awk '{print $2}' | awk -F. '{print $1"."$2"."$3-1}')
+      #     CHART_NAME=$(grep 'name:' Chart.yaml | awk '{print $2}')
+      #     jf rt dl "helm-local/my-chart-$PREVIOUS_VERSION.tgz" --flat
 
-          if [[ -f "my-chart-$PREVIOUS_VERSION.tgz" ]]; then
-            echo "Previous version ($PREVIOUS_VERSION) found. Checking for backward compatibility..."
+      #     if [[ -f "my-chart-$PREVIOUS_VERSION.tgz" ]]; then
+      #       echo "Previous version ($PREVIOUS_VERSION) found. Checking for backward compatibility..."
 
-            # Render templates for the new and previous versions
-            helm template . > new-version.yaml
-            helm template $CHART_NAME-$PREVIOUS_VERSION.tgz > previous-version.yaml
+      #       # Render templates for the new and previous versions
+      #       helm template . > new-version.yaml
+      #       helm template $CHART_NAME-$PREVIOUS_VERSION.tgz > previous-version.yaml
 
-            # Compare the rendered templates
-            if ! diff -u previous-version.yaml new-version.yaml; then
-              echo "❌ Backward-incompatible changes detected!"
-              exit 1
-            else
-              echo "✅ No backward-incompatible changes detected."
-            fi
-          else
-            echo "No previous version found. Skipping backward compatibility check."
-          fi
+      #       # Compare the rendered templates
+      #       if ! diff -u previous-version.yaml new-version.yaml; then
+      #         echo "❌ Backward-incompatible changes detected!"
+      #         exit 1
+      #       else
+      #         echo "✅ No backward-incompatible changes detected."
+      #       fi
+      #     else
+      #       echo "No previous version found. Skipping backward compatibility check."
+      #     fi
 
       - name: Package Helm Chart
         run: |
           cd ${{ inputs.chart_path }}
           helm package . --app-version $(grep 'version:' Chart.yaml | awk '{print $2}')
+          ls
           mv *.tgz ../../
 
       - name: Run Trivy vulnerability scanner in IaC mode
@@ -98,30 +93,30 @@ jobs:
           TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
           TRIVY_DISABLE_VEX_NOTICE: true
 
-      - name: Set up JFrog CLI
-        uses: jfrog/setup-jfrog-cli@f748a0599171a192a2668afee8d0497f7c1069df # v4.5.6
+      # - name: Set up JFrog CLI
+      #   uses: jfrog/setup-jfrog-cli@f748a0599171a192a2668afee8d0497f7c1069df # v4.5.6
 
-      - name: Configure JFrog CLI
-        env:
-          ARTIFACTORY_API_TOKEN: ${{ secrets.artifactory_api_token }}
-          JFROG_URL: ${{ inputs.jfrog_url }}
-        run: |
-          echo "${ARTIFACTORY_API_TOKEN}" | jf config add nethermind \
-            --url="${JFROG_URL}" \
-            --interactive=false \
-            --access-token-stdin
+      # - name: Configure JFrog CLI
+      #   env:
+      #     ARTIFACTORY_API_TOKEN: ${{ secrets.artifactory_api_token }}
+      #     JFROG_URL: ${{ inputs.jfrog_url }}
+      #   run: |
+      #     echo "${ARTIFACTORY_API_TOKEN}" | jf config add nethermind \
+      #       --url="${JFROG_URL}" \
+      #       --interactive=false \
+      #       --access-token-stdin
 
-      - name: Publish Helm Chart to JFrog if not Already Exists in JFrog
-        run: |
-          CHART_VERSION=$(grep 'version:' Chart.yaml | awk '{print $2}')
-          CHART_NAME=$(grep 'name:' Chart.yaml | awk '{print $2}')
-          if jf rt s "helm-local/${CHART_NAME}-${CHART_VERSION}.tgz" | grep -q "${CHART_NAME}-${CHART_VERSION}.tgz"; then
-            echo "❌ Helm chart ${CHART_NAME} version ${CHART_VERSION} already exists in JFrog. Please update the version before pushing."
-            exit 1
-          else
-            echo "✅ Helm chart version ${CHART_VERSION} is not found in JFrog. Proceeding with upload..."
-            jf rt u "*.tgz" "helm-local/"
-          fi
+      # - name: Publish Helm Chart to JFrog if not Already Exists in JFrog
+      #   run: |
+      #     CHART_VERSION=$(grep 'version:' Chart.yaml | awk '{print $2}')
+      #     CHART_NAME=$(grep 'name:' Chart.yaml | awk '{print $2}')
+      #     if jf rt s "helm-local/${CHART_NAME}-${CHART_VERSION}.tgz" | grep -q "${CHART_NAME}-${CHART_VERSION}.tgz"; then
+      #       echo "❌ Helm chart ${CHART_NAME} version ${CHART_VERSION} already exists in JFrog. Please update the version before pushing."
+      #       exit 1
+      #     else
+      #       echo "✅ Helm chart version ${CHART_VERSION} is not found in JFrog. Proceeding with upload..."
+      #       jf rt u "*.tgz" "helm-local/"
+      #     fi
 
       - name: Summary
         if: always()
